import argparse
import csv
import time
from pathlib import Path
from typing import Dict, List

from common import (
    build_tokenized_samples,
    ensure_dir,
    evaluate_language_model,
    load_model_and_tokenizer,
    prune_linear_inputs,
    save_json,
    set_seed,
)


def parse_args():
    parser = argparse.ArgumentParser(description="Run AIDCS-style layer-type input sparsity sensitivity experiments.")
    parser.add_argument("--model-path", type=str, default="/home/zh/model/Llama-2-7b-hf")
    parser.add_argument("--datasets", nargs="+", default=["wikitext2", "c4"])
    parser.add_argument("--num-samples", type=int, default=12)
    parser.add_argument("--max-length", type=int, default=256)
    parser.add_argument("--sparsities", nargs="+", type=float, default=[0.4, 0.5, 0.55, 0.6, 0.65])
    parser.add_argument("--target-kinds", nargs="+", default=["qkv", "out", "up", "down"])
    parser.add_argument("--output-dir", type=str, default="aidcs_repro/results/layer_type_sensitivity")
    parser.add_argument("--seed", type=int, default=20260324)
    return parser.parse_args()


def main():
    args = parse_args()
    set_seed(args.seed)
    output_dir = Path(args.output_dir)
    ensure_dir(output_dir)

    print(f"[info] loading model from {args.model_path}")
    model, tokenizer = load_model_and_tokenizer(args.model_path)

    dataset_samples: Dict[str, List] = {}
    for dataset_name in args.datasets:
        print(f"[info] loading dataset samples: {dataset_name}")
        dataset_samples[dataset_name] = build_tokenized_samples(
            tokenizer=tokenizer,
            dataset_name=dataset_name,
            num_samples=args.num_samples,
            max_length=args.max_length,
        )
        print(
            f"[info] dataset={dataset_name} num_samples={len(dataset_samples[dataset_name])} "
            f"avg_len={sum(x.numel() for x in dataset_samples[dataset_name]) / len(dataset_samples[dataset_name]):.1f}"
        )

    rows = []
    summary = {
        "model_path": args.model_path,
        "datasets": args.datasets,
        "target_kinds": args.target_kinds,
        "sparsities": args.sparsities,
        "num_samples": args.num_samples,
        "max_length": args.max_length,
        "results": {},
    }

    for dataset_name, samples in dataset_samples.items():
        print(f"[run] dataset={dataset_name} baseline")
        t0 = time.time()
        baseline = evaluate_language_model(model, samples)
        baseline["runtime_sec"] = time.time() - t0
        summary["results"].setdefault(dataset_name, {})["baseline"] = baseline
        rows.append(
            {
                "dataset": dataset_name,
                "target_kind": "baseline",
                "sparsity": 0.0,
                "loss": baseline["loss"],
                "ppl": baseline["ppl"],
                "delta_ppl_pct": 0.0,
                "runtime_sec": baseline["runtime_sec"],
            }
        )

        for target_kind in args.target_kinds:
            for sparsity in args.sparsities:
                print(f"[run] dataset={dataset_name} target={target_kind} sparsity={sparsity:.2f}")
                t0 = time.time()
                with prune_linear_inputs(model, target_kind=target_kind, sparsity=sparsity):
                    metrics = evaluate_language_model(model, samples)
                runtime_sec = time.time() - t0
                delta_pct = (metrics["ppl"] / baseline["ppl"] - 1.0) * 100.0
                metrics["delta_ppl_pct"] = delta_pct
                metrics["runtime_sec"] = runtime_sec
                summary["results"].setdefault(dataset_name, {}).setdefault(target_kind, {})[str(sparsity)] = metrics
                rows.append(
                    {
                        "dataset": dataset_name,
                        "target_kind": target_kind,
                        "sparsity": sparsity,
                        "loss": metrics["loss"],
                        "ppl": metrics["ppl"],
                        "delta_ppl_pct": delta_pct,
                        "runtime_sec": runtime_sec,
                    }
                )

    csv_path = output_dir / "layer_type_sensitivity.csv"
    with csv_path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(
            f,
            fieldnames=["dataset", "target_kind", "sparsity", "loss", "ppl", "delta_ppl_pct", "runtime_sec"],
        )
        writer.writeheader()
        writer.writerows(rows)

    save_json(summary, output_dir / "layer_type_sensitivity.json")

    latex_lines = [
        "% Auto-generated by aidcs_repro/run_layer_type_sensitivity.py",
        "\\begin{tabular}{c|cccccccc}",
        "\\toprule",
        "\\makecell{Sparsity \\\\ $\\diagdown$ Type-Dataset} & "
        "qkv-wkt2 & qkv-c4 & out-wkt2 & out-c4 & up-wkt2 & up-c4 & down-wkt2 & down-c4 \\\\",
        "\\midrule",
    ]

    baseline_wkt2 = summary["results"].get("wikitext2", {}).get("baseline", {})
    baseline_c4 = summary["results"].get("c4", {}).get("baseline", {})
    if baseline_wkt2 and baseline_c4:
        latex_lines.append(
            f"\\textbf{{baseline}} & {baseline_wkt2['ppl']:.3f} & {baseline_c4['ppl']:.3f} & "
            f"{baseline_wkt2['ppl']:.3f} & {baseline_c4['ppl']:.3f} & "
            f"{baseline_wkt2['ppl']:.3f} & {baseline_c4['ppl']:.3f} & "
            f"{baseline_wkt2['ppl']:.3f} & {baseline_c4['ppl']:.3f} \\\\"
        )

    for sparsity in args.sparsities:
        row_cells = []
        for target_kind in ["qkv", "out", "up", "down"]:
            for dataset_name in ["wikitext2", "c4"]:
                metrics = summary["results"].get(dataset_name, {}).get(target_kind, {}).get(str(sparsity))
                row_cells.append(f"{metrics['ppl']:.3f}" if metrics else "--")
        latex_lines.append(f"{int(round(sparsity * 100))}\\% & " + " & ".join(row_cells) + " \\\\")

    latex_lines.extend(["\\bottomrule", "\\end{tabular}"])
    (output_dir / "layer_type_sensitivity_table.tex").write_text("\n".join(latex_lines), encoding="utf-8")

    print(f"[done] wrote {csv_path}")


if __name__ == "__main__":
    main()
