#!/usr/bin/env bash
set -euo pipefail

CODEX_HOME_DEFAULT="$HOME/.codex"
CODEX_HOME_PATH="${CODEX_HOME:-$CODEX_HOME_DEFAULT}"
CONFIG="$CODEX_HOME_PATH/config.toml"
AUTH="$CODEX_HOME_PATH/auth.json"
TS="$(date +%Y%m%d-%H%M%S)"
BACKUP_DIR="$CODEX_HOME_PATH/backup-shared-sessions-$TS"
BIN_DIR="$HOME/bin"
SHELL_RC=""

choose_shell_rc() {
  if [ -n "${ZSH_VERSION:-}" ] && [ -f "$HOME/.zshrc" ]; then
    SHELL_RC="$HOME/.zshrc"
  elif [ -f "$HOME/.bashrc" ]; then
    SHELL_RC="$HOME/.bashrc"
  elif [ -f "$HOME/.zshrc" ]; then
    SHELL_RC="$HOME/.zshrc"
  else
    SHELL_RC="$HOME/.bashrc"
    touch "$SHELL_RC"
  fi
}

extract_first_base_url() {
  local file="$1"
  if [ -f "$file" ]; then
    awk -F '"' '/^[[:space:]]*base_url[[:space:]]*=[[:space:]]*"/ {print $2; exit}' "$file"
  fi
}

extract_first_model() {
  local file="$1"
  if [ -f "$file" ]; then
    awk -F '"' '/^[[:space:]]*model[[:space:]]*=[[:space:]]*"/ {print $2; exit}' "$file"
  fi
}

extract_root_keys() {
  local file="$1"
  local out="$2"
  : > "$out"
  if [ -f "$file" ]; then
    awk '
      BEGIN { in_table = 0 }
      /^[[:space:]]*\[/ { in_table = 1 }
      {
        if (!in_table) {
          if ($0 ~ /^[[:space:]]*model_provider[[:space:]]*=/) next
          if ($0 ~ /^[[:space:]]*profile[[:space:]]*=/) next
          if ($0 ~ /^[[:space:]]*model[[:space:]]*=/) next
          if ($0 ~ /^[[:space:]]*cli_auth_credentials_store[[:space:]]*=/) next
          print
        }
      }
    ' "$file" > "$out"
  fi
}

slugify_label() {
  printf '%s' "$1" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9_]/_/g'
}

append_once() {
  local line="$1"
  local file="$2"
  grep -Fqx "$line" "$file" 2>/dev/null || printf '%s\n' "$line" >> "$file"
}

mkdir -p "$CODEX_HOME_PATH" "$BIN_DIR" "$BACKUP_DIR"
choose_shell_rc

DEFAULT_A_BASE="$(extract_first_base_url "$CONFIG")"
DEFAULT_MODEL="$(extract_first_model "$CONFIG")"
DEFAULT_MODEL="${DEFAULT_MODEL:-gpt-5.4}"

printf '\n=== Codex shared-session setup ===\n'
printf 'This keeps one shared CODEX_HOME so /resume sees the same local sessions.\n'
printf 'Current CODEX_HOME: %s\n\n' "$CODEX_HOME_PATH"

read -r -p "Current provider label [platform_a]: " A_LABEL
A_LABEL="${A_LABEL:-platform_a}"
A_LABEL="$(slugify_label "$A_LABEL")"
read -r -p "Current provider base_url [${DEFAULT_A_BASE:-https://api.openai.com/v1}]: " A_BASE
A_BASE="${A_BASE:-${DEFAULT_A_BASE:-https://api.openai.com/v1}}"
read -r -p "Current provider env var [CODEX_PLATFORM_A_API_KEY]: " A_ENV
A_ENV="${A_ENV:-CODEX_PLATFORM_A_API_KEY}"

printf '\n'
read -r -p "New provider label [platform_b]: " B_LABEL
B_LABEL="${B_LABEL:-platform_b}"
B_LABEL="$(slugify_label "$B_LABEL")"
read -r -p "New provider base_url [https://api.openai.com/v1]: " B_BASE
B_BASE="${B_BASE:-https://api.openai.com/v1}"
read -r -p "New provider env var [CODEX_PLATFORM_B_API_KEY]: " B_ENV
B_ENV="${B_ENV:-CODEX_PLATFORM_B_API_KEY}"

printf '\n'
read -r -p "Default model [${DEFAULT_MODEL}]: " MODEL_NAME
MODEL_NAME="${MODEL_NAME:-$DEFAULT_MODEL}"

printf '\nYou can paste keys now. Input is hidden. Leave blank if you want to fill them later.\n'
read -r -s -p "$A_ENV: " A_KEY
printf '\n'
read -r -s -p "$B_ENV: " B_KEY
printf '\n\n'

ROOT_TMP="$(mktemp)"
extract_root_keys "$CONFIG" "$ROOT_TMP"

if [ -f "$CONFIG" ]; then cp -a "$CONFIG" "$BACKUP_DIR/"; fi
if [ -f "$AUTH" ]; then cp -a "$AUTH" "$BACKUP_DIR/"; fi
if [ -f "$CODEX_HOME_PATH/history.jsonl" ]; then cp -a "$CODEX_HOME_PATH/history.jsonl" "$BACKUP_DIR/"; fi

cat > "$CONFIG" <<EOF
# Generated by codex_shared_sessions_setup.sh on $TS
# Root keys must appear before tables in TOML.
$(cat "$ROOT_TMP")
profile = "$A_LABEL"
model = "$MODEL_NAME"
cli_auth_credentials_store = "file"

[history]
persistence = "save-all"
max_bytes = 104857600

[model_providers.$A_LABEL]
name = "$A_LABEL"
base_url = "$A_BASE"
wire_api = "responses"
env_key = "$A_ENV"

[model_providers.$B_LABEL]
name = "$B_LABEL"
base_url = "$B_BASE"
wire_api = "responses"
env_key = "$B_ENV"

[profiles.$A_LABEL]
model_provider = "$A_LABEL"
model = "$MODEL_NAME"

[profiles.$B_LABEL]
model_provider = "$B_LABEL"
model = "$MODEL_NAME"
EOF

if [ -f "$AUTH" ]; then
  mv "$AUTH" "$BACKUP_DIR/auth.json.migrated-away"
fi

KEY_FILE="$CODEX_HOME_PATH/provider-keys.sh"
cat > "$KEY_FILE" <<EOF
#!/usr/bin/env bash
# chmod 600 recommended; generated on $TS
export $A_ENV='${A_KEY}'
export $B_ENV='${B_KEY}'
EOF
chmod 600 "$KEY_FILE"

cat > "$BIN_DIR/codex-$A_LABEL" <<EOF
#!/usr/bin/env bash
export CODEX_HOME="$CODEX_HOME_PATH"
[ -f "$KEY_FILE" ] && . "$KEY_FILE"
exec codex --profile "$A_LABEL" "\$@"
EOF
chmod +x "$BIN_DIR/codex-$A_LABEL"

cat > "$BIN_DIR/codex-$B_LABEL" <<EOF
#!/usr/bin/env bash
export CODEX_HOME="$CODEX_HOME_PATH"
[ -f "$KEY_FILE" ] && . "$KEY_FILE"
exec codex --profile "$B_LABEL" "\$@"
EOF
chmod +x "$BIN_DIR/codex-$B_LABEL"

cat > "$BIN_DIR/codex-resume-all" <<EOF
#!/usr/bin/env bash
export CODEX_HOME="$CODEX_HOME_PATH"
[ -f "$KEY_FILE" ] && . "$KEY_FILE"
exec codex resume --all "\$@"
EOF
chmod +x "$BIN_DIR/codex-resume-all"

append_once 'export PATH="$HOME/bin:$PATH"' "$SHELL_RC"
append_once "[ -f \"$KEY_FILE\" ] && . \"$KEY_FILE\"" "$SHELL_RC"

rm -f "$ROOT_TMP"

printf 'Done.\n\n'
printf 'Backup dir: %s\n' "$BACKUP_DIR"
printf 'New config : %s\n' "$CONFIG"
printf 'Key file   : %s\n' "$KEY_FILE"
printf '\nUse these commands after restarting your shell (or run: source %s):\n' "$SHELL_RC"
printf '  source %s\n' "$SHELL_RC"
printf '  codex-%s\n' "$A_LABEL"
printf '  codex-%s\n' "$B_LABEL"
printf '  codex-resume-all\n\n'
printf 'Important: your old auth.json was moved to the backup dir so Codex stops switching cached login state.\n'
printf 'Your local sessions/history under %s were kept in place, so resume continues to use the same session store.\n' "$CODEX_HOME_PATH"

if [ -z "$A_KEY" ] || [ -z "$B_KEY" ]; then
  printf '\nOne or both keys were left blank. Edit %s and fill them in before running Codex.\n' "$KEY_FILE"
fi
